<a href="https://colab.research.google.com/github/codewith-MS/Next_word_Predictor_using_LSTM/blob/main/Next_word_predicting_using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#import library
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd
import numpy as np

#data preprocessing library
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [ ]:
#collecting the data
data = gutenberg.raw('shakespeare-hamlet.txt')
#save the file

save_path = '/content/drive/MyDrive/Project/LSTM/hamlet.txt'

with open(save_path, 'w') as f:
    f.write(data)

In [ ]:
#load the datset

with open(save_path,'r') as file:
      text = file.read().lower()

In [ ]:
#tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words

4818

In [ ]:
total_words

4818

In [ ]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [ ]:
tokenizer.word_docs

defaultdict(int,
            {'barke': 1,
             'promise': 1,
             'fearing': 1,
             'feete': 1,
             'richer': 1,
             'monday': 1,
             'sweete': 1,
             'chariest': 1,
             'departed': 1,
             'strangely': 1,
             'tardie': 1,
             'split': 1,
             'bitter': 1,
             'disease': 1,
             'buyes': 1,
             'guest': 1,
             'oare': 1,
             'lords': 1,
             'conuerse': 1,
             "forg'd": 1,
             'behold': 1,
             'immediate': 1,
             'expend': 1,
             "name's": 1,
             'feast': 1,
             'dore': 1,
             'superfluous': 1,
             'taken': 1,
             "smear'd": 1,
             'weazell': 1,
             'cannoneer': 1,
             'cheerefully': 1,
             'places': 1,
             'recouer': 1,
             "that's": 1,
             'awake': 1,
             'cannon': 1,
   

In [ ]:
#create a input sequence

input_sequence =[]
for line in text.split('\n'):
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    n_gram = token_list[:i+1]
    input_sequence.append(n_gram)

In [ ]:
input_sequence

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [ ]:
#pad sequence - to convert all the sentence into equal length
max_sequence = max([len(x) for x in input_sequence])
max_sequence

14

In [ ]:
#converting the sentence into max length
input_sequence=np.array(pad_sequences(input_sequence,maxlen=max_sequence,padding='pre'))
input_sequence


array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]], dtype=int32)

In [ ]:
#create predicitor and label
import tensorflow as tf
x,y = input_sequence[:,:-1],input_sequence[:,-1]

In [ ]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]], dtype=int32)

In [ ]:
y

array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [ ]:
#converting Y to categorical
y = tf.keras.utils.to_categorical(y,num_classes=total_words)

In [ ]:
y  #wherever the  above index is present in the only there it will be 1 restall zero

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#split the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
## Train our LSTM RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU

## Define the model
model=Sequential()
model.add(Embedding(total_words,100))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_10 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_11 (LSTM)                  │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
## Train the model
history=model.fit(X_train,y_train,epochs=50,validation_data=(X_test,y_test),verbose=1)

Epoch 1/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 49s 68ms/step - accuracy: 0.0320 - loss: 7.1402 - val_accuracy: 0.0418 - val_loss: 6.7516
Epoch 2/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 44s 68ms/step - accuracy: 0.0385 - loss: 6.4740 - val_accuracy: 0.0427 - val_loss: 6.8317
Epoch 3/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 45s 70ms/step - accuracy: 0.0449 - loss: 6.2920 - val_accuracy: 0.0492 - val_loss: 6.8980
Epoch 4/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 44s 68ms/step - accuracy: 0.0505 - loss: 6.1789 - val_accuracy: 0.0532 - val_loss: 6.8863
Epoch 5/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 44s 68ms/step - accuracy: 0.0520 - loss: 6.0433 - val_accuracy: 0.0552 - val_loss: 6.9353
Epoch 6/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 44s 68ms/step - accuracy: 0.0607 - loss: 5.9016 - val_accuracy: 0.0596 - val_loss: 7.0037
Epoch 7/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 44s 68ms/step - accuracy: 0.0694 - loss: 5.7303 - val_accuracy: 0.0596 - val_loss: 7.0346
Epoch 8/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 83s 69ms/step - accuracy: 0.0786 - loss: 5.5911 - 

In [ ]:
##the accuracy of the mode is less

In [ ]:
# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]

    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1

    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)

    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

Step	What it does
- 1	Convert input text to sequence of numbers	“the cat” → [1, 2]
- 2	Trim to correct length	[1, 2] → [1, 2] (if short enough)
- 3	Pad to fixed size	[0, 0, 1, 2]
- 4	Model predicts probabilities	[0.1, 0.05, 0.7, 0.15]
- 5	Pick highest probability index	2
- 6	Convert index to word	“cat”
- 7	Return predicted word	“cat”

In [ ]:
##test the model
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:To be or not to be
Next Word PRediction:done


In [ ]:
#save the model to pickle file

## Save the model
model_path = '/content/drive/MyDrive/Project/LSTM/next_word_lstm.h5'
model.save(model_path)

## Save the tokenizer
import pickle
save_tokenizer = '/content/drive/MyDrive/Project/LSTM/tokenizer.pickle'
with open(save_tokenizer,'wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
input_text="  Barn. Last night of all,When yond same"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:  Barn. Last night of all,When yond same
Next Word PRediction:strict
